### PR TITLE
This is for armhf

### PR DESCRIPTION
**Pull request by JunNineKim**
this is for armhf.

### CODE REVIEW

**Comment by manbearwiz** [comment]
Is there a reason to not use the [official arm python image](https://hub.docker.com/r/arm32v6/python/)? Also could you create a separate file for it, something like `Dockerfile.arm32v6`, rather than overriding the base one?

**Comment by JunNineKim** [comment]
Hi,
I did't know the official arm python image.
Then, I Tried to create image for my ARMv7 Processor first.
I have created Dockerfile.arm32v7 file.
Please, check it.

**Comment by JunNineKim** [comment]
Hi,
I just see "Image Variants" of https://hub.docker.com/r/arm32v7/python/ on bottom side,
"arm32v7/python:<version>-alpine"

Then, I recreate it just before.
I will pull request it later.

**Comment by manbearwiz** [comment]
Looking into this more, it seems like the correct way to handle this now is via [`docker manifest lists`](https://docs.docker.com/engine/reference/commandline/manifest/). Going to look into this more to see the best way to do automated builds for different architectures.

**Comment by manbearwiz** [comment]
Superseded by https://github.com/manbearwiz/youtube-dl-server/pull/166

**Pull request closed without merging**
